#!/bin/bash

# Stiky's BSPWMRC file! :D

bspc monitor LVDS-1 -d 1 2 3
bspc monitor VGA-1 -d 4 5 6

bspc config border_width 2
bspc config window_gap 15

bspc config focus_follows_pointer false
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config remove_unplugged_monitors true
bspc config click_to_focus true

# Autolaunch programs!

pkill sxhkd
pkill polybar
sxhkd -c ~/.config/sxhkd/sxhkdrc &
polybar &
plank &
dunst &
mpd &
picom &
lxpolkit &
nitrogen --restore
rofi -show drun
